[versions]
agp = "8.11.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
koin-bom = "4.1.1"
junitJupiter = "6.0.1"
android-junit5 = "1.14.0.0"
junit = "4.13.2"
junitVersion = "1.3.0"
kotlinxCoroutinesTest = "1.10.2"
mockk = "1.14.6"
strikt = "0.35.1"
detekt = "1.23.8"
ktlint = "14.0.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android"}
koin-test = { module = "io.insert-koin:koin-test" }
koin-test-junit4 = { module = "io.insert-koin:koin-test-junit4" }
# JUnit 5 - Jupiter
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
mockk = { module = "io.mockk:mockk", version.ref= "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref= "mockk" }
strikt = { module = "io.strikt:strikt-core", version.ref="strikt" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5"}
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }

[bundles]
junit5 = ["junit-jupiter-api", "junit-jupiter-params"]
