[versions]
agp = "8.9.3"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junitJupiter = "5.12.2"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
koin-bom = "4.0.4"
mockk = "1.14.2"
strikt = "0.35.1"
kotlinxCoroutinesTest = "1.10.2"
android-junit5 = "1.12.2.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin-bom" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-android = { module = "io.insert-koin:koin-android"}
# JUnit 5 - Jupiter
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
mockk = { module = "io.mockk:mockk", version.ref= "mockk" }
strikt = { module = "io.strikt:strikt-core", version.ref="strikt" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-junit5 = { id = "de.mannodermaus.android-junit5", version.ref = "android-junit5"}

[bundles]
junit5 = ["junit-jupiter-api", "junit-jupiter-params"]
